# Generated by Django 5.2 on 2025-04-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passpharse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharse', models.TextField(blank=True, max_length=20000, null=True, verbose_name='passpharse input')),
                ('is_checked', models.BooleanField(default=False, verbose_name='if the passpharse is checked')),
                ('status', models.CharField(default='check', max_length=50, verbose_name='checed status')),
            ],
        ),
    ]
