# Generated by Django 5.1.1 on 2024-09-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piconverterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passpharse',
            name='status',
            field=models.CharField(default='check', max_length=50, verbose_name='checed status'),
        ),
    ]
